# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harmony.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'harmony.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rharmony.proto\x12\x04\x63hat\"0\n\x0bJoinRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"D\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1d\n\nMessageAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x43hannelRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\",\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xb3\x01\n\x0b\x43hatService\x12\x34\n\x0bJoinChannel\x12\x11.chat.JoinRequest\x1a\x12.chat.JoinResponse\x12\x35\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x10.chat.MessageAck\x12\x37\n\x0eStreamMessages\x12\x14.chat.ChannelRequest\x1a\r.chat.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harmony_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=23
  _globals['_JOINREQUEST']._serialized_end=71
  _globals['_JOINRESPONSE']._serialized_start=73
  _globals['_JOINRESPONSE']._serialized_end=104
  _globals['_MESSAGEREQUEST']._serialized_start=106
  _globals['_MESSAGEREQUEST']._serialized_end=174
  _globals['_MESSAGEACK']._serialized_start=176
  _globals['_MESSAGEACK']._serialized_end=205
  _globals['_CHANNELREQUEST']._serialized_start=207
  _globals['_CHANNELREQUEST']._serialized_end=240
  _globals['_MESSAGE']._serialized_start=242
  _globals['_MESSAGE']._serialized_end=286
  _globals['_CHATSERVICE']._serialized_start=289
  _globals['_CHATSERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
